AWSTemplateFormatVersion: '2010-09-09'
Description: ForensIQ Core Infrastructure

Parameters:
  Environment:
    Type: String
    Default: staging
  BucketName:
    Type: String
  TableName:
    Type: String

Resources:
  EvidenceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: ForensIQ

  CaseMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: case_id
          AttributeType: S
        - AttributeName: filename
          AttributeType: S
      KeySchema:
        - AttributeName: case_id
          KeyType: HASH
        - AttributeName: filename
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: ForensIQ

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ForensIQLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ForensIQLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:UpdateItem
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Scan
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

Outputs:
  BucketName:
    Value: !Ref EvidenceBucket
  TableName:
    Value: !Ref CaseMetadataTable
  LambdaExecutionRoleArn:
    Value: !GetAtt LambdaExecutionRole.Arn